name = "quizterm"
version = "0.5.0"

[dependencies]
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 3.7.2 and < 5.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"
mist = ">= 5.0.0 and < 6.0.0"
lustre = ">= 5.3.5 and < 6.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"
group_registry = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_stdlib = ">= 0.65.0 and < 1.0.0"
